spring.application.name=spring-batch-chunks
# Spring Batch
spring.batch.job.enabled=true
spring.batch.jdbc.initialize-database=always

# Base de datos (usando H2 en memoria)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true